version: "2"
services:
  dockerico:
    build: ./dockeri.co
    container_name: dockerico
    networks:
      - wblankenship
    restart: always
  ssb:
    build: ./easy-ssb-pub
    container_name: ssb
    environment:
      HOST: "45.55.167.102"
    networks:
      - wblankenship
    volumes:
      - ./.ssb:/root/.ssb
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - wblankenship
    restart: always
    volumes:
      - ./nginx/dockerico.conf:/etc/nginx/conf.d/dockerico.conf:ro
      - ./nginx/ssb.conf:/etc/nginx/conf.d/ssb.conf:ro
      - ./logs:/var/log/nginx
    volumes_from:
      - dockerico
      - ssb
    ports:
      - 80:80
      - 8008:8008
      - 8007:8007
networks:
  wblankenship:
    driver: bridge
