version: "2"
services:
  dockerico:
    build: ./dockeri.co
    container_name: dockerico
    networks:
      - wblankenship
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - wblankenship
    restart: always
    volumes:
      - ./nginx/dockerico.conf:/etc/nginx/conf.d/dockerico.conf:ro
      - ./nginx/wblankenship.conf:/etc/nginx/conf.d/wblankenship.conf:ro
      - ./logs:/var/log/nginx
      - ./nginx/wblankenship/_site:/var/www/wblankenship:ro
    volumes_from:
      - dockerico
    ports:
      - 80:80
      - 8008:8008
      - 8007:8007
networks:
  wblankenship:
    driver: bridge
